/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderId = IDL.Nat;
export const RestaurantId = IDL.Nat;
export const MenuItemId = IDL.Nat;
export const MenuItemVariant = IDL.Record({
  'name' : IDL.Text,
  'price' : IDL.Float64,
});
export const MenuItem = IDL.Record({
  'id' : MenuItemId,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'variants' : IDL.Vec(MenuItemVariant),
  'restaurantId' : RestaurantId,
  'isVeg' : IDL.Bool,
  'price' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RestaurantStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'suspended' : IDL.Null,
});
export const RestaurantProfile = IDL.Record({
  'id' : RestaurantId,
  'status' : RestaurantStatus,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'cuisineType' : IDL.Text,
  'address' : IDL.Text,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'readyForPickup' : IDL.Null,
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'placed' : IDL.Null,
  'pickedUp' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Time = IDL.Int;
export const CartItem = IDL.Record({
  'quantity' : IDL.Nat,
  'menuItemId' : MenuItemId,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'customer' : IDL.Principal,
  'createdAt' : Time,
  'deliveryPartner' : IDL.Opt(IDL.Principal),
  'items' : IDL.Vec(CartItem),
  'totalPrice' : IDL.Float64,
  'restaurant' : RestaurantId,
});
export const AppRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'deliveryPartner' : IDL.Null,
  'restaurantOwner' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'restaurantIds' : IDL.Vec(RestaurantId),
  'deliveryAddress' : IDL.Opt(IDL.Text),
  'appRole' : AppRole,
  'name' : IDL.Text,
  'isApprovedDeliveryPartner' : IDL.Bool,
  'phone' : IDL.Text,
});
export const PublicUserProfile = IDL.Record({
  'id' : IDL.Principal,
  'appRole' : AppRole,
  'name' : IDL.Text,
  'isApprovedDeliveryPartner' : IDL.Bool,
});
export const Review = IDL.Record({
  'customer' : IDL.Principal,
  'createdAt' : Time,
  'orderId' : OrderId,
  'comment' : IDL.Text,
  'rating' : IDL.Float64,
  'restaurant' : RestaurantId,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptDelivery' : IDL.Func([OrderId], [], []),
  'addMenuItem' : IDL.Func([RestaurantId, MenuItem], [MenuItemId], []),
  'addReview' : IDL.Func(
      [RestaurantId, OrderId, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'addToCart' : IDL.Func([MenuItemId, IDL.Nat], [], []),
  'approveDeliveryPartner' : IDL.Func([IDL.Principal], [], []),
  'approveRestaurant' : IDL.Func([RestaurantId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createRestaurant' : IDL.Func([RestaurantProfile], [RestaurantId], []),
  'deleteMenuItem' : IDL.Func([MenuItemId], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllRestaurants' : IDL.Func([], [IDL.Vec(RestaurantProfile)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAvailableDeliveries' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getMenuItems' : IDL.Func([RestaurantId], [IDL.Vec(MenuItem)], ['query']),
  'getMyDeliveries' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyRestaurants' : IDL.Func([], [IDL.Vec(RestaurantProfile)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getPendingDeliveryPartners' : IDL.Func(
      [],
      [IDL.Vec(PublicUserProfile)],
      ['query'],
    ),
  'getPendingRestaurants' : IDL.Func(
      [],
      [IDL.Vec(RestaurantProfile)],
      ['query'],
    ),
  'getRestaurant' : IDL.Func(
      [RestaurantId],
      [IDL.Opt(RestaurantProfile)],
      ['query'],
    ),
  'getRestaurantOrders' : IDL.Func([RestaurantId], [IDL.Vec(Order)], ['query']),
  'getRestaurantReviews' : IDL.Func(
      [RestaurantId],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'placeOrder' : IDL.Func([RestaurantId], [OrderId], []),
  'removeFromCart' : IDL.Func([MenuItemId], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchRestaurants' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RestaurantProfile)],
      ['query'],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'suspendRestaurant' : IDL.Func([RestaurantId], [], []),
  'unsuspendRestaurant' : IDL.Func([RestaurantId], [], []),
  'updateDeliveryStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateMenuItem' : IDL.Func(
      [
        MenuItemId,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Bool,
        IDL.Bool,
        IDL.Vec(MenuItemVariant),
      ],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateRestaurant' : IDL.Func(
      [RestaurantId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderId = IDL.Nat;
  const RestaurantId = IDL.Nat;
  const MenuItemId = IDL.Nat;
  const MenuItemVariant = IDL.Record({
    'name' : IDL.Text,
    'price' : IDL.Float64,
  });
  const MenuItem = IDL.Record({
    'id' : MenuItemId,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'variants' : IDL.Vec(MenuItemVariant),
    'restaurantId' : RestaurantId,
    'isVeg' : IDL.Bool,
    'price' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RestaurantStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const RestaurantProfile = IDL.Record({
    'id' : RestaurantId,
    'status' : RestaurantStatus,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'cuisineType' : IDL.Text,
    'address' : IDL.Text,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'readyForPickup' : IDL.Null,
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'placed' : IDL.Null,
    'pickedUp' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Time = IDL.Int;
  const CartItem = IDL.Record({
    'quantity' : IDL.Nat,
    'menuItemId' : MenuItemId,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'customer' : IDL.Principal,
    'createdAt' : Time,
    'deliveryPartner' : IDL.Opt(IDL.Principal),
    'items' : IDL.Vec(CartItem),
    'totalPrice' : IDL.Float64,
    'restaurant' : RestaurantId,
  });
  const AppRole = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'deliveryPartner' : IDL.Null,
    'restaurantOwner' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'restaurantIds' : IDL.Vec(RestaurantId),
    'deliveryAddress' : IDL.Opt(IDL.Text),
    'appRole' : AppRole,
    'name' : IDL.Text,
    'isApprovedDeliveryPartner' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const PublicUserProfile = IDL.Record({
    'id' : IDL.Principal,
    'appRole' : AppRole,
    'name' : IDL.Text,
    'isApprovedDeliveryPartner' : IDL.Bool,
  });
  const Review = IDL.Record({
    'customer' : IDL.Principal,
    'createdAt' : Time,
    'orderId' : OrderId,
    'comment' : IDL.Text,
    'rating' : IDL.Float64,
    'restaurant' : RestaurantId,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptDelivery' : IDL.Func([OrderId], [], []),
    'addMenuItem' : IDL.Func([RestaurantId, MenuItem], [MenuItemId], []),
    'addReview' : IDL.Func(
        [RestaurantId, OrderId, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'addToCart' : IDL.Func([MenuItemId, IDL.Nat], [], []),
    'approveDeliveryPartner' : IDL.Func([IDL.Principal], [], []),
    'approveRestaurant' : IDL.Func([RestaurantId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createRestaurant' : IDL.Func([RestaurantProfile], [RestaurantId], []),
    'deleteMenuItem' : IDL.Func([MenuItemId], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllRestaurants' : IDL.Func([], [IDL.Vec(RestaurantProfile)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAvailableDeliveries' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getMenuItems' : IDL.Func([RestaurantId], [IDL.Vec(MenuItem)], ['query']),
    'getMyDeliveries' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyRestaurants' : IDL.Func([], [IDL.Vec(RestaurantProfile)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getPendingDeliveryPartners' : IDL.Func(
        [],
        [IDL.Vec(PublicUserProfile)],
        ['query'],
      ),
    'getPendingRestaurants' : IDL.Func(
        [],
        [IDL.Vec(RestaurantProfile)],
        ['query'],
      ),
    'getRestaurant' : IDL.Func(
        [RestaurantId],
        [IDL.Opt(RestaurantProfile)],
        ['query'],
      ),
    'getRestaurantOrders' : IDL.Func(
        [RestaurantId],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getRestaurantReviews' : IDL.Func(
        [RestaurantId],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'placeOrder' : IDL.Func([RestaurantId], [OrderId], []),
    'removeFromCart' : IDL.Func([MenuItemId], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchRestaurants' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RestaurantProfile)],
        ['query'],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'suspendRestaurant' : IDL.Func([RestaurantId], [], []),
    'unsuspendRestaurant' : IDL.Func([RestaurantId], [], []),
    'updateDeliveryStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateMenuItem' : IDL.Func(
        [
          MenuItemId,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Bool,
          IDL.Bool,
          IDL.Vec(MenuItemVariant),
        ],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateRestaurant' : IDL.Func(
        [RestaurantId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };