/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'admin' : null } |
  { 'customer' : null } |
  { 'deliveryPartner' : null } |
  { 'restaurantOwner' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface CartItem { 'quantity' : bigint, 'menuItemId' : MenuItemId }
export interface MenuItem {
  'id' : MenuItemId,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'variants' : Array<MenuItemVariant>,
  'restaurantId' : RestaurantId,
  'isVeg' : boolean,
  'price' : number,
}
export type MenuItemId = bigint;
export interface MenuItemVariant { 'name' : string, 'price' : number }
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'customer' : Principal,
  'createdAt' : Time,
  'deliveryPartner' : [] | [Principal],
  'items' : Array<CartItem>,
  'totalPrice' : number,
  'restaurant' : RestaurantId,
}
export type OrderId = bigint;
export type OrderStatus = { 'readyForPickup' : null } |
  { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'placed' : null } |
  { 'pickedUp' : null } |
  { 'delivered' : null } |
  { 'accepted' : null };
export interface PublicUserProfile {
  'id' : Principal,
  'appRole' : AppRole,
  'name' : string,
  'isApprovedDeliveryPartner' : boolean,
}
export type RestaurantId = bigint;
export interface RestaurantProfile {
  'id' : RestaurantId,
  'status' : RestaurantStatus,
  'owner' : Principal,
  'name' : string,
  'cuisineType' : string,
  'address' : string,
  'rating' : number,
  'phone' : string,
}
export type RestaurantStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'suspended' : null };
export interface Review {
  'customer' : Principal,
  'createdAt' : Time,
  'orderId' : OrderId,
  'comment' : string,
  'rating' : number,
  'restaurant' : RestaurantId,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'restaurantIds' : Array<RestaurantId>,
  'deliveryAddress' : [] | [string],
  'appRole' : AppRole,
  'name' : string,
  'isApprovedDeliveryPartner' : boolean,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptDelivery' : ActorMethod<[OrderId], undefined>,
  'addMenuItem' : ActorMethod<[RestaurantId, MenuItem], MenuItemId>,
  'addReview' : ActorMethod<[RestaurantId, OrderId, number, string], undefined>,
  'addToCart' : ActorMethod<[MenuItemId, bigint], undefined>,
  'approveDeliveryPartner' : ActorMethod<[Principal], undefined>,
  'approveRestaurant' : ActorMethod<[RestaurantId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createRestaurant' : ActorMethod<[RestaurantProfile], RestaurantId>,
  'deleteMenuItem' : ActorMethod<[MenuItemId], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllRestaurants' : ActorMethod<[], Array<RestaurantProfile>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAvailableDeliveries' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getMenuItems' : ActorMethod<[RestaurantId], Array<MenuItem>>,
  'getMyDeliveries' : ActorMethod<[], Array<Order>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyRestaurants' : ActorMethod<[], Array<RestaurantProfile>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getPendingDeliveryPartners' : ActorMethod<[], Array<PublicUserProfile>>,
  'getPendingRestaurants' : ActorMethod<[], Array<RestaurantProfile>>,
  'getRestaurant' : ActorMethod<[RestaurantId], [] | [RestaurantProfile]>,
  'getRestaurantOrders' : ActorMethod<[RestaurantId], Array<Order>>,
  'getRestaurantReviews' : ActorMethod<[RestaurantId], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'placeOrder' : ActorMethod<[RestaurantId], OrderId>,
  'removeFromCart' : ActorMethod<[MenuItemId], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchRestaurants' : ActorMethod<[string], Array<RestaurantProfile>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'suspendRestaurant' : ActorMethod<[RestaurantId], undefined>,
  'unsuspendRestaurant' : ActorMethod<[RestaurantId], undefined>,
  'updateDeliveryStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateMenuItem' : ActorMethod<
    [
      MenuItemId,
      string,
      string,
      number,
      boolean,
      boolean,
      Array<MenuItemVariant>,
    ],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateRestaurant' : ActorMethod<
    [RestaurantId, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];