/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Review {
    customer: Principal;
    createdAt: Time;
    orderId: OrderId;
    comment: string;
    rating: number;
    restaurant: RestaurantId;
}
export type Time = bigint;
export interface MenuItemVariant {
    name: string;
    price: number;
}
export type RestaurantId = bigint;
export interface Order {
    id: OrderId;
    status: OrderStatus;
    customer: Principal;
    createdAt: Time;
    deliveryPartner?: Principal;
    items: Array<CartItem>;
    totalPrice: number;
    restaurant: RestaurantId;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface PublicUserProfile {
    id: Principal;
    appRole: AppRole;
    name: string;
    isApprovedDeliveryPartner: boolean;
}
export type MenuItemId = bigint;
export interface MenuItem {
    id: MenuItemId;
    name: string;
    isAvailable: boolean;
    description: string;
    variants: Array<MenuItemVariant>;
    restaurantId: RestaurantId;
    isVeg: boolean;
    price: number;
}
export interface CartItem {
    quantity: bigint;
    menuItemId: MenuItemId;
}
export interface RestaurantProfile {
    id: RestaurantId;
    status: RestaurantStatus;
    owner: Principal;
    name: string;
    cuisineType: string;
    address: string;
    rating: number;
    phone: string;
}
export type OrderId = bigint;
export interface UserProfile {
    restaurantIds: Array<RestaurantId>;
    deliveryAddress?: string;
    appRole: AppRole;
    name: string;
    isApprovedDeliveryPartner: boolean;
    phone: string;
}
export enum AppRole {
    admin = "admin",
    customer = "customer",
    deliveryPartner = "deliveryPartner",
    restaurantOwner = "restaurantOwner"
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum OrderStatus {
    readyForPickup = "readyForPickup",
    preparing = "preparing",
    cancelled = "cancelled",
    placed = "placed",
    pickedUp = "pickedUp",
    delivered = "delivered",
    accepted = "accepted"
}
export enum RestaurantStatus {
    active = "active",
    pending = "pending",
    suspended = "suspended"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptDelivery(orderId: OrderId): Promise<void>;
    addMenuItem(restaurantId: RestaurantId, item: MenuItem): Promise<MenuItemId>;
    addReview(restaurantId: RestaurantId, orderId: OrderId, rating: number, comment: string): Promise<void>;
    addToCart(menuItemId: MenuItemId, quantity: bigint): Promise<void>;
    approveDeliveryPartner(user: Principal): Promise<void>;
    approveRestaurant(restaurantId: RestaurantId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearCart(): Promise<void>;
    createRestaurant(profile: RestaurantProfile): Promise<RestaurantId>;
    deleteMenuItem(menuItemId: MenuItemId): Promise<void>;
    getAllOrders(): Promise<Array<Order>>;
    getAllRestaurants(): Promise<Array<RestaurantProfile>>;
    getAllUsers(): Promise<Array<[Principal, UserProfile]>>;
    getAvailableDeliveries(): Promise<Array<Order>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<Array<CartItem>>;
    getMenuItems(restaurantId: RestaurantId): Promise<Array<MenuItem>>;
    getMyDeliveries(): Promise<Array<Order>>;
    getMyOrders(): Promise<Array<Order>>;
    getMyRestaurants(): Promise<Array<RestaurantProfile>>;
    getOrder(orderId: OrderId): Promise<Order | null>;
    getPendingDeliveryPartners(): Promise<Array<PublicUserProfile>>;
    getPendingRestaurants(): Promise<Array<RestaurantProfile>>;
    getRestaurant(restaurantId: RestaurantId): Promise<RestaurantProfile | null>;
    getRestaurantOrders(restaurantId: RestaurantId): Promise<Array<Order>>;
    getRestaurantReviews(restaurantId: RestaurantId): Promise<Array<Review>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    placeOrder(restaurantId: RestaurantId): Promise<OrderId>;
    removeFromCart(menuItemId: MenuItemId): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchRestaurants(searchTerm: string): Promise<Array<RestaurantProfile>>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    suspendRestaurant(restaurantId: RestaurantId): Promise<void>;
    unsuspendRestaurant(restaurantId: RestaurantId): Promise<void>;
    updateDeliveryStatus(orderId: OrderId, status: OrderStatus): Promise<void>;
    updateMenuItem(menuItemId: MenuItemId, name: string, description: string, price: number, isVeg: boolean, isAvailable: boolean, variants: Array<MenuItemVariant>): Promise<void>;
    updateOrderStatus(orderId: OrderId, status: OrderStatus): Promise<void>;
    updateRestaurant(restaurantId: RestaurantId, name: string, cuisineType: string, address: string, phone: string): Promise<void>;
}
import type { AppRole as _AppRole, ApprovalStatus as _ApprovalStatus, CartItem as _CartItem, Order as _Order, OrderId as _OrderId, OrderStatus as _OrderStatus, PublicUserProfile as _PublicUserProfile, RestaurantId as _RestaurantId, RestaurantProfile as _RestaurantProfile, RestaurantStatus as _RestaurantStatus, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptDelivery(arg0: OrderId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptDelivery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptDelivery(arg0);
            return result;
        }
    }
    async addMenuItem(arg0: RestaurantId, arg1: MenuItem): Promise<MenuItemId> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(arg0, arg1);
            return result;
        }
    }
    async addReview(arg0: RestaurantId, arg1: OrderId, arg2: number, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addToCart(arg0: MenuItemId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1);
            return result;
        }
    }
    async approveDeliveryPartner(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveDeliveryPartner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveDeliveryPartner(arg0);
            return result;
        }
    }
    async approveRestaurant(arg0: RestaurantId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveRestaurant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveRestaurant(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async createRestaurant(arg0: RestaurantProfile): Promise<RestaurantId> {
        if (this.processError) {
            try {
                const result = await this.actor.createRestaurant(to_candid_RestaurantProfile_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRestaurant(to_candid_RestaurantProfile_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteMenuItem(arg0: MenuItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0);
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRestaurants(): Promise<Array<RestaurantProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRestaurants();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRestaurants();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableDeliveries(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableDeliveries();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableDeliveries();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return result;
        }
    }
    async getMenuItems(arg0: RestaurantId): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItems(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItems(arg0);
            return result;
        }
    }
    async getMyDeliveries(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDeliveries();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDeliveries();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRestaurants(): Promise<Array<RestaurantProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRestaurants();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRestaurants();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingDeliveryPartners(): Promise<Array<PublicUserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingDeliveryPartners();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingDeliveryPartners();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingRestaurants(): Promise<Array<RestaurantProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingRestaurants();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingRestaurants();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurant(arg0: RestaurantId): Promise<RestaurantProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurant(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurant(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurantOrders(arg0: RestaurantId): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurantOrders(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurantOrders(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurantReviews(arg0: RestaurantId): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurantReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurantReviews(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: RestaurantId): Promise<OrderId> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0);
            return result;
        }
    }
    async removeFromCart(arg0: MenuItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchRestaurants(arg0: string): Promise<Array<RestaurantProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchRestaurants(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchRestaurants(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n42(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n42(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async suspendRestaurant(arg0: RestaurantId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendRestaurant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendRestaurant(arg0);
            return result;
        }
    }
    async unsuspendRestaurant(arg0: RestaurantId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsuspendRestaurant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsuspendRestaurant(arg0);
            return result;
        }
    }
    async updateDeliveryStatus(arg0: OrderId, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeliveryStatus(arg0, to_candid_OrderStatus_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeliveryStatus(arg0, to_candid_OrderStatus_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMenuItem(arg0: MenuItemId, arg1: string, arg2: string, arg3: number, arg4: boolean, arg5: boolean, arg6: Array<MenuItemVariant>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateRestaurant(arg0: RestaurantId, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRestaurant(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRestaurant(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_AppRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PublicUserProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicUserProfile): PublicUserProfile {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_RestaurantProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RestaurantProfile): RestaurantProfile {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_RestaurantStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RestaurantStatus): RestaurantStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestaurantProfile]): RestaurantProfile | null {
    return value.length === 0 ? null : from_candid_RestaurantProfile_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RestaurantId;
    status: _RestaurantStatus;
    owner: Principal;
    name: string;
    cuisineType: string;
    address: string;
    rating: number;
    phone: string;
}): {
    id: RestaurantId;
    status: RestaurantStatus;
    owner: Principal;
    name: string;
    cuisineType: string;
    address: string;
    rating: number;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_RestaurantStatus_n16(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        name: value.name,
        cuisineType: value.cuisineType,
        address: value.address,
        rating: value.rating,
        phone: value.phone
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    restaurantIds: Array<_RestaurantId>;
    deliveryAddress: [] | [string];
    appRole: _AppRole;
    name: string;
    isApprovedDeliveryPartner: boolean;
    phone: string;
}): {
    restaurantIds: Array<RestaurantId>;
    deliveryAddress?: string;
    appRole: AppRole;
    name: string;
    isApprovedDeliveryPartner: boolean;
    phone: string;
} {
    return {
        restaurantIds: value.restaurantIds,
        deliveryAddress: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.deliveryAddress)),
        appRole: from_candid_AppRole_n23(_uploadFile, _downloadFile, value.appRole),
        name: value.name,
        isApprovedDeliveryPartner: value.isApprovedDeliveryPartner,
        phone: value.phone
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    appRole: _AppRole;
    name: string;
    isApprovedDeliveryPartner: boolean;
}): {
    id: Principal;
    appRole: AppRole;
    name: string;
    isApprovedDeliveryPartner: boolean;
} {
    return {
        id: value.id,
        appRole: from_candid_AppRole_n23(_uploadFile, _downloadFile, value.appRole),
        name: value.name,
        isApprovedDeliveryPartner: value.isApprovedDeliveryPartner
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n36(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    customer: Principal;
    createdAt: _Time;
    deliveryPartner: [] | [Principal];
    items: Array<_CartItem>;
    totalPrice: number;
    restaurant: _RestaurantId;
}): {
    id: OrderId;
    status: OrderStatus;
    customer: Principal;
    createdAt: Time;
    deliveryPartner?: Principal;
    items: Array<CartItem>;
    totalPrice: number;
    restaurant: RestaurantId;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n10(_uploadFile, _downloadFile, value.status),
        customer: value.customer,
        createdAt: value.createdAt,
        deliveryPartner: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.deliveryPartner)),
        items: value.items,
        totalPrice: value.totalPrice,
        restaurant: value.restaurant
    };
}
function from_candid_tuple_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n20(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    readyForPickup: null;
} | {
    preparing: null;
} | {
    cancelled: null;
} | {
    placed: null;
} | {
    pickedUp: null;
} | {
    delivered: null;
} | {
    accepted: null;
}): OrderStatus {
    return "readyForPickup" in value ? OrderStatus.readyForPickup : "preparing" in value ? OrderStatus.preparing : "cancelled" in value ? OrderStatus.cancelled : "placed" in value ? OrderStatus.placed : "pickedUp" in value ? OrderStatus.pickedUp : "delivered" in value ? OrderStatus.delivered : "accepted" in value ? OrderStatus.accepted : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    suspended: null;
}): RestaurantStatus {
    return "active" in value ? RestaurantStatus.active : "pending" in value ? RestaurantStatus.pending : "suspended" in value ? RestaurantStatus.suspended : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    customer: null;
} | {
    deliveryPartner: null;
} | {
    restaurantOwner: null;
}): AppRole {
    return "admin" in value ? AppRole.admin : "customer" in value ? AppRole.customer : "deliveryPartner" in value ? AppRole.deliveryPartner : "restaurantOwner" in value ? AppRole.restaurantOwner : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RestaurantProfile>): Array<RestaurantProfile> {
    return value.map((x)=>from_candid_RestaurantProfile_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicUserProfile>): Array<PublicUserProfile> {
    return value.map((x)=>from_candid_PublicUserProfile_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_RestaurantProfile_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantProfile): _RestaurantProfile {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_RestaurantStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantStatus): _RestaurantStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    restaurantIds: Array<RestaurantId>;
    deliveryAddress?: string;
    appRole: AppRole;
    name: string;
    isApprovedDeliveryPartner: boolean;
    phone: string;
}): {
    restaurantIds: Array<_RestaurantId>;
    deliveryAddress: [] | [string];
    appRole: _AppRole;
    name: string;
    isApprovedDeliveryPartner: boolean;
    phone: string;
} {
    return {
        restaurantIds: value.restaurantIds,
        deliveryAddress: value.deliveryAddress ? candid_some(value.deliveryAddress) : candid_none(),
        appRole: to_candid_AppRole_n40(_uploadFile, _downloadFile, value.appRole),
        name: value.name,
        isApprovedDeliveryPartner: value.isApprovedDeliveryPartner,
        phone: value.phone
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: RestaurantId;
    status: RestaurantStatus;
    owner: Principal;
    name: string;
    cuisineType: string;
    address: string;
    rating: number;
    phone: string;
}): {
    id: _RestaurantId;
    status: _RestaurantStatus;
    owner: Principal;
    name: string;
    cuisineType: string;
    address: string;
    rating: number;
    phone: string;
} {
    return {
        id: value.id,
        status: to_candid_RestaurantStatus_n5(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        name: value.name,
        cuisineType: value.cuisineType,
        address: value.address,
        rating: value.rating,
        phone: value.phone
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    admin: null;
} | {
    customer: null;
} | {
    deliveryPartner: null;
} | {
    restaurantOwner: null;
} {
    return value == AppRole.admin ? {
        admin: null
    } : value == AppRole.customer ? {
        customer: null
    } : value == AppRole.deliveryPartner ? {
        deliveryPartner: null
    } : value == AppRole.restaurantOwner ? {
        restaurantOwner: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    readyForPickup: null;
} | {
    preparing: null;
} | {
    cancelled: null;
} | {
    placed: null;
} | {
    pickedUp: null;
} | {
    delivered: null;
} | {
    accepted: null;
} {
    return value == OrderStatus.readyForPickup ? {
        readyForPickup: null
    } : value == OrderStatus.preparing ? {
        preparing: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.placed ? {
        placed: null
    } : value == OrderStatus.pickedUp ? {
        pickedUp: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantStatus): {
    active: null;
} | {
    pending: null;
} | {
    suspended: null;
} {
    return value == RestaurantStatus.active ? {
        active: null
    } : value == RestaurantStatus.pending ? {
        pending: null
    } : value == RestaurantStatus.suspended ? {
        suspended: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
